[toolchain]
anchor_version = "0.31.0"
solana_version = "2.2.2"

[features]
seeds = false
skip-lint = false

# Program ID will be managed by our automated scripts
# Make sure to deploy with properly synced files:
# make deploy-and-sync-all
[programs.localnet]
s3mt_presale = "5tz5xFvHNnJViiCZ3iHdgqrTC1GfcEvnB49KoxvQpR3D"

# Use the same program ID across all networks
[programs.devnet]
s3mt_presale = "5tz5xFvHNnJViiCZ3iHdgqrTC1GfcEvnB49KoxvQpR3D"

[programs.testnet]
s3mt_presale = "5tz5xFvHNnJViiCZ3iHdgqrTC1GfcEvnB49KoxvQpR3D"

[programs.mainnet]
s3mt_presale = "5tz5xFvHNnJViiCZ3iHdgqrTC1GfcEvnB49KoxvQpR3D"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "./test-keypair.json"

[scripts]
test = "ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[workspace]
members = ["."]

[test]
startup_wait = 5000

[test.validator]
url = "https://api.mainnet-beta.solana.com"

[build]
sbf = true 