services:
  traefik:
    container_name: traefik
    image: traefik:${TRAEFIK_IMAGE_TAG:-latest}
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
