#!/bin/sh -x

_forwardTerm() {
  echo "Caught signal SIGTERM, passing it to child processes..."
  pgrep -P $$ | xargs kill -15 2>/dev/null
  wait
  exit $?
}

trap _forwardTerm TERM

_setupLogs() {
  local service="$1"
  local num_procs="$2"

  procs="$(seq 0 $(($num_procs - 1)))"

  for i in $procs; do
    touch "/var/log/supervisor/${service}-0${i}.log"
    chown nobody:nobody "/var/log/supervisor/${service}-0${i}.log"
  done

  tail -f /var/log/supervisor/${service}-*.log &
}

_writeConfig() {
  local service="$1"
  local num_procs="$2"
  local port_base="$3"

  procs="$(seq 0 $(($num_procs - 1)))"

  for i in $procs; do
    echo "$service-0$i going to /etc/haproxy/cfg/haproxy_$service.cfg"

    echo "" >>/etc/haproxy/cfg/haproxy_$service.cfg
    echo "    server $service-0$i 127.0.0.1:$port_base$i check" >>/etc/haproxy/cfg/haproxy_$service.cfg
  done
}

_configureHAProxy() {
  local image_version=$1
  local nuxt_num_procs=$2

  echo "Configure haproxy with: IMAGE_VERSION=$image_version, NUXT_NUM_PROCS=$nuxt_num_procs"

  echo "" >/etc/haproxy/cfg/servers.cfg

  _writeConfig app $nuxt_num_procs 300

  echo "" >/etc/haproxy/haproxy.cfg

  cat /etc/haproxy/cfg/*.cfg >/etc/haproxy/haproxy.cfg

  cat /etc/haproxy/haproxy.cfg
}

_main() {
  export NUXT_NUM_PROCS=${NUXT_NUM_PROCS:-$([[ "$CANONICAL_URL" =~ "localhost" ]] && echo 1 || echo 4)}
  export NUXT_COMMAND=${NUXT_COMMAND:-$([[ "$CANONICAL_URL" =~ "localhost" ]] && echo "/usr/local/bin/server -s nuxt -D" || echo "/usr/local/bin/server -s nuxt")}
  #export NUXT_COMMAND="/usr/local/bin/server -s nuxt -D"
  

  _setupLogs nuxt $NUXT_NUM_PROCS

  echo "Starting nuxt via supervisor with: NUXT_NUM_PROCS=$NUXT_NUM_PROCS, NUXT_COMMAND=$NUXT_COMMAND"


  mkdir /app/.nuxt
  chown -R nobody:nobody /app/.nuxt

  /usr/bin/supervisord -c "/etc/supervisor/conf.d/app.conf"

  _configureHAProxy $IMAGE_VERSION $NUXT_NUM_PROCS

  #if [ -n "$HOST_NAME" ]; then
  #  echo "Provisioning JIT SSL for $APP_HOST"
  #  provision-jit-ssl $APP_HOST
  #fi

  exec haproxy -W -db -f /etc/haproxy/haproxy.cfg
}

if [ $# -eq 0 ]; then
  _main
else
  exec "$@"
fi
