name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  build-and-push-s3mt-xyz:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run make build
        run: |
          source docker/compose/.env
          make build s=${PROJECT}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: web-mech
          password: ${{ secrets.PACKAGE_SECRET }}

      - name: Push Docker image
        run: |
          source docker/compose/.env
          docker push ghcr.io/${ORGANIZATION}/${PROJECT}:$S3MT_XYZ_IMAGE_TAG

  build-and-push-traefik:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run make build
        run: |
          source docker/compose/.env
          make build s=traefik

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: web-mech
          password: ${{ secrets.PACKAGE_SECRET }}

      - name: Push Docker image
        run: |
          source docker/compose/.env
          docker push ghcr.io/${ORGANIZATION}/traefik:${TRAEFIK_IMAGE_TAG}
    
